analytics: {}
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0
  lightness: 0.445101
  rhythmicContrast: 0.490709
  saturation: 0
cta: {}
layout_spectrum: 0.2635649052860457
name: arielperino
opengraph: {}
purpose: {}
typography_spectrum: 0.914351276295866
